		<div class="hero-unit media">		
			<div class="media-body">
				<h3>About the Author</h3>
				<img src="/bimg/main profile.jpg" class="img-rounded">
				<p>Trevor Stokes is a young tech enthusiast interested in many aspects of technology, but particularly with regard to how business and technology can work together cohesively to benefit people.</p>
				
				<p>Trevor&#39;s academic and professional background provides a solid foundation of principles that lay credence to his current and future endeavors.</p>
				
				<ul>
					<li>MBA &#45; Illinois State University, 2011</li>
					<li>Bachelors, Computer Information Systems &#45; Ferris State University, 2007</li>
					<li>Systems Analyst &#45; State Farm Insurance, 2007 &#45; June 2013</li>
					<li>Business Analyst &#45; State Farm Insurance, 2010 &#45; 2011</li>
					<li>Volunteer and Member &#45; Association of Information Technology Professionals, 2005 &#45; Current</li>
					<li>Advisory Board Member &#45; Ferris State University CIS Department, 2007 &#45; Current</li>
				</ul>
				
				<p>Always seeking to improve himself, some of Trevor&#39;s current goals are:</p>
				
				<ul>
					<li>Learn to speak Spanish fluently &#45; 2013</li>
					<li>Launch a web startup &#45; 2013</li>
				</ul>
				
				<p>For more information on Trevor, visit his <a href="http://www.linkedin.com/pub/trevor-stokes/7/986/155/" target="_blank">LinkedIn</a> or <a href="https://plus.google.com/107119416021617345395/about" target="_blank">Google+</a> pages.</p>
				
				<br><h3>About the Website</h3>
				
				<p>This website is meant to act as a platform for Trevor to communicate his thoughts on business and technology to the world. Hopefully the website will stimulate thought-provoking discussions and address real world business and technology issues. Change is not always easy or welcomed, but with the internet (and sites like this one), change always has a voice.</p>
			</div>
		</div>
		<?php echo $this->partial('blogNav'); ?>
