		<!-- This well is for blog post content. One blog post at a time. -->
		<div class="well well-large">
			<h3>I am alive!</h3>
			<p>Some of you may have been watching this website for updates that I promised were on the way. If you are one of those people, I would like to first thank you and secondly apologize that I haven&#39;t been more active on this site. Having recently moved to Huntington Beach, CA I have been pretty busy with that lately and haven&#39;t had a good chance yet to post on this site.</p>
			
			<p>This site may be undergoing a host change and/or redesign. If so, that will be taking precedence over new posts on this blog. It may also mean that this website will be unavailable or incomplete for some time. All I can ask is that you be patient during this transition period. In the meantime, if anyone has any suggestions of topics you&#39;d like me to discuss please let me know in the comments. Thanks!</p>

		</div>

		<!-- Use older newer buttons to show older/newer blog post -->
		<ul class="pager">
			<li class="previous disabled">
				<a href="#">&larr; Older</a>
			</li>
			<li class="next">
				<a href="#">Newer &rarr;</a>
			</li>
		</ul>