<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('A Blog by Trevor Stokes')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
		<div class="page-header" style="padding-left:20px">
			<h1>Business and Technology - A Reasoned View <br><small>by Trevor Stokes</small></h1>
		</div>
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li <?php if (strpos("//" . $_SERVER['REQUEST_URI'], "home")) echo "class='active'"; ?>><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li <?php if (strpos("//" . $_SERVER['REQUEST_URI'], "posts")) echo "class='active'"; ?>><a href="<?php echo $this->url('posts') ?>"><?php echo $this->translate('Blog Posts') ?></a></li>
                        <li <?php if (strpos("//" . $_SERVER['REQUEST_URI'], "about")) echo "class='active'"; ?>><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
		
			<div class="tabbable">
				<ul class="nav nav-tabs">
					<li <?php if (!strpos("//" . $_SERVER['REQUEST_URI'], "posts")) echo "class='active'"; ?>>
						<a href="#tab1" data-toggle="tab">Recent Posts</a>
					</li>
					<li>
						<a href="#tab2" data-toggle="tab">Archive</a>
					</li>
					<?php if (strpos("//" . $_SERVER['REQUEST_URI'], "posts")) echo "<li class='active'><a href='#tab3' data-toggle='tab'>Comments</a></li>"; ?>
				</ul>
				<div class="tab-content">
					<div class="tab-pane<?php if (!strpos("//" . $_SERVER['REQUEST_URI'], "posts")) echo " active"; ?>" id="tab1">
						<p>Recent</p>
					</div>
					<div class="tab-pane" id="tab2">
						<p>Archive</p>
					</div>
					<?php 
					if (strpos("//" . $_SERVER['REQUEST_URI'], "posts")) 
						echo "
					<div class='tab-pane active' id='tab3'>
					<br />
						<!-- Form and button to add new comments -->
						<form method='post' class='form-horizontal' role='form'>
							<div class='form-group' style='width:300px'>
								<input class='form-control' type='text' name='name' id='name' placeholder='Display Name' />
								<br />
								<input class='form-control' type='text' name='email' id='email' placeholder='Email Address' />
							</div>
							<div class='form-group' style='width:500px'>
								<textarea class='form-control' rows='5' class='input-xlarge' placeholder='Comment'></textarea>
								<br />
								<button type='submit' class='btn'>Submit Comment</button>
							</div>
						</form>
					</div>";
					?>
				</div>
			</div>
            <hr>
            <footer>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
