		<div class="hero-unit media">
			<img class="media-object pull-right" src="/bimg/main profile.jpg">		
			<div class="media-body">
				<h2>Welcome to my Blog</h2>
				<p>My name is Trevor Stokes. I am a tech enthusiast, albeit with often critical views of the industry. This site is a platform for presenting my opinions on various business and technology related topics.</p>
				
				<p>I try my best to consider all perspectives when writing critiques, and will try to incorporate that sensibility along with my rationale in all of my blog posts. I welcome any and all comments, whether they challenge my views or not.</p>
				
				<p>Together, we all can learn from each other!</p>
			</div>
		</div>
		
		<div class="tabbable">
			<ul class="nav nav-tabs">
				<li class="active">
					<a href="#tab1" data-toggle="tab">Recent Posts</a>
				</li>
				<li>
					<a href="#tab2" data-toggle="tab">Recent Comments</a>
				</li>
				<li>
					<a href="#tab3" data-toggle="tab">Archive</a>
				</li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<p>Recent posts here!</p>
				</div>
				<div class="tab-pane" id="tab2">
					<p>Recent comments here!</p>
				</div>
				<div class="tab-pane" id="tab3">
					<p>Archives here!</p>
				</div>
			</div>
		</div>